name: Python Package Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install pytest streamlit detoxify torch transformers numpy --extra-index-url https://pytorch.org
    - name: Test with pytest
      run: |
        pytest test_shield.py
